spring:
  application:
    name: smallCinema
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
logging.level.root: INFO
resource:
  OMDb-movies-url: ${OMDB_MOVIES_URL}
  OMDb-apiKey: ${OMDB_API_KEY}
---
## Profile for local executions through IDE or mvn CLI
spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: [your-database-url] #example: jdbc:postgresql://localhost:5432/postgres
    username: [your-database-username] # example: postgres
    password: [your-database-password] #example: mysecretpassword
resource:
  OMDb-movies-url: http://www.omdbapi.com/?apikey=
  OMDb-apiKey: [your-OMDb-apiKey]
